<?php
// This file is part of Moodle - https://moodle.org/

defined('MOODLE_INTERNAL') || die();

$functions = [
    'local_api_moodle_get_site_structure' => [
        'classname' => 'local_api_moodle_external',
        'methodname' => 'get_site_structure',
        'classpath' => 'local/api_moodle/externallib.php',
        'description' => 'Return a lightweight category structure for the mobile app.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/api_moodle:use',
    ],
    'local_api_moodle_search_courses' => [
        'classname' => 'local_api_moodle_external',
        'methodname' => 'search_courses',
        'classpath' => 'local/api_moodle/externallib.php',
        'description' => 'Search visible courses with mobile-safe fields.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/api_moodle:use',
    ],
    'local_api_moodle_get_mobile_dashboard' => [
        'classname' => 'local_api_moodle_external',
        'methodname' => 'get_mobile_dashboard',
        'classpath' => 'local/api_moodle/externallib.php',
        'description' => 'Return a compact dashboard payload for authenticated mobile users.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/api_moodle:use',
    ],
    'local_api_moodle_get_my_courses' => [
        'classname' => 'local_api_moodle_external',
        'methodname' => 'get_my_courses',
        'classpath' => 'local/api_moodle/externallib.php',
        'description' => 'Return enrolled courses for the authenticated user.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/api_moodle:use',
    ],
    'local_api_moodle_get_course_detail' => [
        'classname' => 'local_api_moodle_external',
        'methodname' => 'get_course_detail',
        'classpath' => 'local/api_moodle/externallib.php',
        'description' => 'Return a single course detail and section summary.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/api_moodle:use',
    ],
    'local_api_moodle_get_course_contents' => [
        'classname' => 'local_api_moodle_external',
        'methodname' => 'get_course_contents',
        'classpath' => 'local/api_moodle/externallib.php',
        'description' => 'Return lightweight course sections and activities.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/api_moodle:use',
    ],
    'local_api_moodle_get_assignments' => [
        'classname' => 'local_api_moodle_external',
        'methodname' => 'get_assignments',
        'classpath' => 'local/api_moodle/externallib.php',
        'description' => 'Return assignments and current user submission status.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/api_moodle:use',
    ],
    'local_api_moodle_get_quizzes' => [
        'classname' => 'local_api_moodle_external',
        'methodname' => 'get_quizzes',
        'classpath' => 'local/api_moodle/externallib.php',
        'description' => 'Return quizzes and current user attempt status.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/api_moodle:use',
    ],
    'local_api_moodle_get_grades' => [
        'classname' => 'local_api_moodle_external',
        'methodname' => 'get_grades',
        'classpath' => 'local/api_moodle/externallib.php',
        'description' => 'Return current user grade items for one course.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/api_moodle:use',
    ],
    'local_api_moodle_get_calendar_events' => [
        'classname' => 'local_api_moodle_external',
        'methodname' => 'get_calendar_events',
        'classpath' => 'local/api_moodle/externallib.php',
        'description' => 'Return upcoming calendar events visible to the authenticated user.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/api_moodle:use',
    ],
    'local_api_moodle_get_notifications' => [
        'classname' => 'local_api_moodle_external',
        'methodname' => 'get_notifications',
        'classpath' => 'local/api_moodle/externallib.php',
        'description' => 'Return popup notifications for the authenticated user.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/api_moodle:use',
    ],
    'local_api_moodle_mark_notification_read' => [
        'classname' => 'local_api_moodle_external',
        'methodname' => 'mark_notification_read',
        'classpath' => 'local/api_moodle/externallib.php',
        'description' => 'Mark one popup notification as read.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'local/api_moodle:use',
    ],
    'local_api_moodle_get_teaching_overview' => [
        'classname' => 'local_api_moodle_external',
        'methodname' => 'get_teaching_overview',
        'classpath' => 'local/api_moodle/externallib.php',
        'description' => 'Return compact teaching summary for lecturers.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => 'local/api_moodle:use',
    ],
];

$services = [
    'USU Mobile API Gateway' => [
        'functions' => array_keys($functions),
        'restrictedusers' => 1,
        'enabled' => 0,
        'shortname' => 'local_api_moodle_mobile',
        'downloadfiles' => 1,
        'uploadfiles' => 0,
    ],
];
